
server:
  port: 8082
  servlet:
    context-path: 
    
# Oracle #
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: DEVSU
    password: 123
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect         
        #'[globally_quoted_identifiers]': true#
    show-sql: true
    hibernate:
      ddl-auto: update