--  We Create a new scheme
CREATE USER TEST IDENTIFIED BY 123
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS;

-- We assign permissions for start session, create tables, etc.

GRANT CREATE TABLE , CREATE SESSION, CREATE VIEW , CREATE ANY TRIGGER, CREATE ANY PROCEDURE, CREATE SEQUENCE TO TEST;

-- Script for create the database to users

CREATE TABLE PERSONA(
 	ID_PERSONA NUMBER(4,0) NOT NULL PRIMARY KEY, 
	NOMBRES VARCHAR2(120 BYTE) NOT NULL UNIQUE, 
	GENERO VARCHAR2(20 BYTE) NOT NULL , 
	IDENTIFI VARCHAR2(20 BYTE)NOT NULL,
	DIRECCION VARCHAR2(200 BYTE)NOT NULL,
	TELEFONO VARCHAR2(50 BYTE) NOT NULL
 );
 
CREATE SEQUENCE SEQ_PERSONA;

CREATE TABLE CLIENTE(
 	ID_CLIENTE NUMBER(4,0) NOT NULL PRIMARY KEY, 	
	CONTRASEÑA VARCHAR2(20 BYTE) NOT NULL,
	ESTADO CHAR(1 BYTE) DEFAULT 1 NOT NULL,
	ID_PERSONA NUMBER(4,0) NOT NULL, 
	CONSTRAINT CLIENTE_PERSONA_FK FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(ID_PERSONA)
 );
 
CREATE SEQUENCE SEQ_CLIENTE;

CREATE TABLE CUENTA(
 	ID_CUENTA NUMBER(4,0) NOT NULL PRIMARY KEY, 	
	NUM_CUENTA VARCHAR2(20 BYTE) NOT NULL,
	TIP_CUENTA VARCHAR2(50 BYTE) NOT NULL,
	SALDO_INIT NUMERIC,
	ESTADO CHAR(1 BYTE) DEFAULT 1 NOT NULL,
	ID_CLIENTE NUMBER(4,0) NOT NULL,
	CONSTRAINT CUENTA_CLIENTE_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
 );
 
CREATE SEQUENCE SEQ_CUENTA;

CREATE TABLE MOVIMIENTOS(
 	ID_MOVIMIENTO NUMBER(4,0) NOT NULL PRIMARY KEY, 
	FECHA_MOV DATE DEFAULT SYSDATE,
	TIP_MOV VARCHAR2(50 BYTE) NOT NULL,
	VALOR NUMERIC NOT NULL,
	SALDO NUMERIC NOT NULL,
	ID_CUENTA NUMBER(4,0) NOT NULL, 
	CONSTRAINT MOVIMIENTO_CUENTA_FK FOREIGN KEY (ID_CUENTA) REFERENCES CUENTA(ID_CUENTA)
 );
 
CREATE SEQUENCE SEQ_MOVIMIENTOS;
